--1. Which Geo-political zone has the highest number of health professionals and the area with the lowest?
SELECT L.REGION,
	SUM(P.NUM_OF_DOCS) AS NUM_DOCS,
	SUM(P.NUM_OF_PHARMS) AS NUM_OF_PHARMS,
	SUM(P.NUM_OF_MIDWIFES) AS NUM_MIDWIFES,
	SUM(P.NUM_OF_NURSES) AS NUM_NURSES,
	SUM(P.NUM_OF_NURSE_MIDWIFE) AS NURSE_MIDWIFE,
	SUM(P.NUM_OF_PHARM_TECHNICIANS) AS PHARM_TECHNICIANS,
	SUM(P.NUM_OF_DENTISTS) AS NUM_DENTISTS,
	SUM(P.NUM_OF_HEALTH_ATTENDANTS) AS NUM_HEALTH_ATTENDANTS,
	SUM(P.NUM_OF_ENV_HEALTH_OFFICERS) AS NUM_ENV_HEALTH_OFFICERS,
	SUM(P.NUM_OF_HIM_OFFICERS) AS NUM_HIM_OFFICERS,
	SUM(P.NUM_OF_COMMUNITY_HEALTH_OFFICER) AS NUM_HEALTH_OFFICER,
	SUM(P.NUM_OF_JUN_COMMUNITY_EXTENSION_WORKER) AS HUN_COMM_EXT,
	SUM(P.NUM_OF_COMMUNITY_EXTENSION_WORKERS) AS NUM_COMM_EXT,
	SUM(P.NUM_OF_DENTAL_TECHNICIANS) AS DENTAL_TECHNICIANS,
	SUM(P.NUM_OF_LAB_TECHNICIANS) AS MUM_LAB_TECH,
	SUM(P.NUM_OF_LAB_SCIENTISTS) AS NUM_LAB_SCIENTISTS
		
FROM LOCATIONS L
JOIN PERSONNEL P ON L.FACILITY_UID = P.FACILITY_UID
GROUP BY 1

SELECT L.REGION,
    COALESCE(SUM(P.NUM_OF_DOCS), 0) + COALESCE(SUM(P.NUM_OF_PHARMS), 0) + COALESCE(SUM(P.NUM_OF_MIDWIFES), 0) + COALESCE(SUM(P.NUM_OF_NURSES), 0) + COALESCE(SUM(P.NUM_OF_NURSE_MIDWIFE), 0) + COALESCE(SUM(P.NUM_OF_PHARM_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_DENTISTS), 0) + COALESCE(SUM(P.NUM_OF_HEALTH_ATTENDANTS), 0) + COALESCE(SUM(P.NUM_OF_ENV_HEALTH_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_HIM_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_HEALTH_OFFICER), 0) + COALESCE(SUM(P.NUM_OF_JUN_COMMUNITY_EXTENSION_WORKER), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_EXTENSION_WORKERS), 0) + COALESCE(SUM(P.NUM_OF_DENTAL_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_SCIENTISTS), 0) AS TOTAL_PERSONNEL
FROM LOCATIONS L
JOIN PERSONNEL P ON L.FACILITY_UID = P.FACILITY_UID
WHERE L.REGION IS NOT NULL
GROUP BY L.REGION;

--The North West region has the highest number of health professionals


--2. What is the distribution of health professionals across the country? Do we have more Doctors, Nurses or Lab scientists?
--Distribution of health professionals across the country by State
SELECT PA.STATE,
		SUM(PE.NUM_OF_DOCS) AS NUMBER_OF_DOCS,
		SUM(PE.NUM_OF_NURSES) AS NUMBER_OF_NURSES,
		SUM(PE.NUM_OF_LAB_SCIENTISTS) AS LAB_SCIENTISTS
FROM PAGES PA
JOIN PERSONNEL PE
ON PA.FACILITY_UID = PE.FACILITY_UID
GROUP BY 1
ORDER BY 1

-- Total number of health professionals across the country
SELECT 
		SUM(PE.NUM_OF_DOCS) AS NUMBER_OF_DOCTORS,
		SUM(PE.NUM_OF_NURSES) AS NUMBER_OF_NURSES,
		SUM(PE.NUM_OF_LAB_SCIENTISTS) AS NUMBER_LAB_SCIENTISTS
FROM PAGES PA
JOIN PERSONNEL PE
ON PA.FACILITY_UID = PE.FACILITY_UID


--3. What's the average number of beds per facility? Are there facilities that do not have beds at all? 
--If yes, which facility and what state?
SELECT *
FROM
	(SELECT P.STATE,
			P.FACILITY_NAME,
			ROUND(AVG(S.TOT_NUM_BEDS::INT), 1) AS AVERAGE_NUMBER_OF_BEDS
	FROM PAGES P
	JOIN SERVICES S
	ON P.FACILITY_UID = S.FACILITY_UID
	GROUP BY 1, 2) T1
WHERE T1.AVERAGE_NUMBER_OF_BEDS = 0.0


--4. Which year had the highest number of health facilities inaugurated?
SELECT DATE_PART('YEAR', START_DATE), COUNT(*)
FROM IDENTIFIERS
GROUP BY 1
ORDER BY 2 DESC

--THE YEAR 2000 HAD THE HIGHEST NUMBER OF HEALTH FACILITIES INAUGURATED WITH 2064 FACILITIES


--5. Do privately owned facilities have more health personnel than Public?
SELECT I.OWNERSHIP,
    COALESCE(SUM(P.NUM_OF_DOCS), 0) + COALESCE(SUM(P.NUM_OF_PHARMS), 0) + COALESCE(SUM(P.NUM_OF_MIDWIFES), 0) + COALESCE(SUM(P.NUM_OF_NURSES), 0) + COALESCE(SUM(P.NUM_OF_NURSE_MIDWIFE), 0) + COALESCE(SUM(P.NUM_OF_PHARM_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_DENTISTS), 0) + COALESCE(SUM(P.NUM_OF_HEALTH_ATTENDANTS), 0) + COALESCE(SUM(P.NUM_OF_ENV_HEALTH_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_HIM_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_HEALTH_OFFICER), 0) + COALESCE(SUM(P.NUM_OF_JUN_COMMUNITY_EXTENSION_WORKER), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_EXTENSION_WORKERS), 0) + COALESCE(SUM(P.NUM_OF_DENTAL_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_SCIENTISTS), 0) AS TOTAL_PERSONNEL
FROM IDENTIFIERS I
JOIN PERSONNEL P ON I.FACILITY_UID = P.FACILITY_UID
WHERE I.OWNERSHIP IS NOT NULL
GROUP BY 1;

--THERE ARE MORE HEALTH PROFESSIONALS IN PUBLIC OWNED FACILITIES(222,247) THAN PRIVATE OWNED FACILITIES(99937)

--6. Which state has the highest number of privately owned health facilities?
SELECT P.STATE, 
		I.OWNERSHIP, 
		COUNT(*) AS NUMBER_OF_FACILITIES
FROM PAGES P
JOIN IDENTIFIERS I
ON P.FACILITY_UID = I.FACILITY_UID
WHERE I.OWNERSHIP = 'Private'
GROUP BY 1, 2
ORDER BY 3 desc

-- Lagos State has the highest number of privately owned health facilities with 1,568 

-- 7. Are there regions and facilities with no health personnel? What year were they inaugurated? 
-- Are they privately or publicly owned, and what is the Facility level?
SELECT *
FROM
	(SELECT L.REGION,
			PA.FACILITY_NAME,
			PA.FACILITY_LEVEL,
			PA.OWNERSHIP,
			I.START_DATE,
			COALESCE(SUM(P.NUM_OF_DOCS), 0) + COALESCE(SUM(P.NUM_OF_PHARMS), 0) + COALESCE(SUM(P.NUM_OF_MIDWIFES), 0) + COALESCE(SUM(P.NUM_OF_NURSES), 0) + COALESCE(SUM(P.NUM_OF_NURSE_MIDWIFE), 0) + COALESCE(SUM(P.NUM_OF_PHARM_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_DENTISTS), 0) + COALESCE(SUM(P.NUM_OF_HEALTH_ATTENDANTS), 0) + COALESCE(SUM(P.NUM_OF_ENV_HEALTH_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_HIM_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_HEALTH_OFFICER), 0) + COALESCE(SUM(P.NUM_OF_JUN_COMMUNITY_EXTENSION_WORKER), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_EXTENSION_WORKERS), 0) + COALESCE(SUM(P.NUM_OF_DENTAL_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_SCIENTISTS), 0) AS TOTAL_PERSONNEL
	FROM LOCATIONS L
	JOIN PERSONNEL P ON L.FACILITY_UID = P.FACILITY_UID
	JOIN PAGES PA
	ON PA.FACILITY_UID = P.FACILITY_UID
	JOIN IDENTIFIERS I
	ON I.FACILITY_UID = PA.FACILITY_UID
	WHERE L.REGION IS NOT NULL 
	GROUP BY 1, 2, 3, 4, 5)T1
WHERE T1.TOTAL_PERSONNEL = 0
ORDER BY T1.REGION;

--8. Which facility has the lowest hour of operation? What's the operation hour?
SELECT FACILITY_NAME, HOURS_OF_OPERATION
FROM IDENTIFIERS
WHERE HOURS_OF_OPERATION IS NOT NULL
GROUP BY 1, 2

SELECT FACILITY_NAME, 
       REGEXP_REPLACE(HOURS_OF_OPERATION, '[^0-9]*([0-9]{2}).*', '\\1') AS HOURS_OF_OPERATION
FROM IDENTIFIERS
WHERE HOURS_OF_OPERATION IS NOT NULL
GROUP BY 1, 2;

-- 9. Which state has the highest number of unlicensed health facilities?
SELECT P.STATE, S.LICENSE_STATUS, COUNT(*) AS COUNTER
FROM PAGES P
JOIN STATUS S
ON P.FACILITY_UID = S.FACILITY_UID
WHERE S.LICENSE_STATUS IS NOT NULL AND S.LICENSE_STATUS = 'Not Licensed'
GROUP BY 1, 2
ORDER BY 3 DESC

--Oyo State has the highest number of Unlicensed health facilities with 56

--10. Which state has the highest number of licensed health facilities?
SELECT P.STATE, S.LICENSE_STATUS, COUNT(*) AS COUNTER
FROM PAGES P
JOIN STATUS S
ON P.FACILITY_UID = S.FACILITY_UID
WHERE S.LICENSE_STATUS IS NOT NULL AND S.LICENSE_STATUS = 'Licensed'
GROUP BY 1, 2
ORDER BY 3 DESC

--Lagos State has the highest number of Licensed health facilities with 1552

--11. What is the ratio of Doctors to Nurses in each State?
SELECT PA.STATE, AVG(PE.NUM_OF_DOCS / (PE.NUM_OF_NURSES + 0.001)) AS RATIO
FROM PAGES PA
JOIN PERSONNEL PE ON PA.FACILITY_UID = PE.FACILITY_UID
GROUP BY PA.STATE
ORDER BY PA.STATE;



--13. First established Facility per LGA
SELECT T2.FACILITY, T3.LGA_NAME, T3.START_DATEE
FROM
	(SELECT P.LGA AS LG_NAME,
		P.FACILITY_NAME AS FACILITY,
		MIN(I.START_DATE) AS ST_DATE
	FROM PAGES P
	JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID
	GROUP BY 1,2
	ORDER BY 1, 3) T2

JOIN
	(SELECT P.LGA AS LGA_NAME,
		MIN(I.START_DATE) AS START_DATEE
	FROM PAGES P
	JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID
	GROUP BY 1
	ORDER BY 1) T3
ON T3.LGA_NAME = T2.LG_NAME AND T3.START_DATEE = T2.ST_DATE
ORDER BY 3;
	

--14: How many facilities per LGA & Ward with their corresponding total per LGA and Ward separately.

SELECT lga, ward, COUNT(*) AS num_facilities,
       SUM(COUNT(*)) OVER (PARTITION BY lga) AS total_facilities_per_lga,
       SUM(COUNT(*)) OVER (PARTITION BY ward) AS total_facilities_per_ward
FROM locations
GROUP BY lga, ward;

--15. What facilities/facility have their tenure above the average facility tenure in their Ward as of today


--16. Write a query to select earliet and latest Facilities per ward
SELECT T3.WARD, T2.FACILITY_NAME, T2.START_DATE --, T3.EARLIEST_FACILITY, T3.LATEST_FACILITY
FROM
    (SELECT P.FACILITY_NAME, P.WARD, I.START_DATE
     FROM PAGES P
     JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID) T2
JOIN
    (SELECT P.WARD, MIN(I.START_DATE) AS EARLIEST_FACILITY, MAX(I.START_DATE) AS LATEST_FACILITY
     FROM PAGES P
     JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID
     GROUP BY P.WARD) T3
ON T2.WARD = T3.WARD AND (T2.START_DATE = T3.EARLIEST_FACILITY OR T2.START_DATE = T3.LATEST_FACILITY)
ORDER BY T3.WARD, T2.START_DATE;


--17. When (in years) is the duration between the latest and earliest Facility per ward in each LGA.

SELECT T4.LG, T4.DURATION
FROM
	(SELECT T2.LG, T3.WARD, T2.FACILITY_NAME, (DATE_PART('YEAR', T3.LATEST_FACILITY) - DATE_PART('YEAR',T3.EARLIEST_FACILITY) ) AS DURATION
		FROM
			(SELECT P.FACILITY_NAME, P.LGA AS LG, P.WARD, I.START_DATE
			 FROM PAGES P
			 JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID) T2
		JOIN
			(SELECT P.WARD, P.LGA AS LG_2, MIN(I.START_DATE) AS EARLIEST_FACILITY, MAX(I.START_DATE) AS LATEST_FACILITY
			 FROM PAGES P
			 JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID
			 GROUP BY P.WARD, P.LGA) T3
		ON T2.WARD = T3.WARD AND T2.LG = T3.LG_2 AND (T2.START_DATE = T3.EARLIEST_FACILITY OR T2.START_DATE = T3.LATEST_FACILITY)
		ORDER BY T3.WARD, T2.START_DATE)T4
GROUP BY 1, 2
ORDER BY 2;

--18. What is the 3-years moving average of facility establishment per State
						  
SELECT p.state, DATE_PART('YEAR', i.start_date),
       AVG(DATE_PART('YEAR', i.start_date::date))
           OVER (PARTITION BY p.state
                 ORDER BY DATE_PART('YEAR', i.start_date)
                 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS three_year_moving_avg
FROM PAGES P
JOIN IDENTIFIERS I ON P.FACILITY_UID = I.FACILITY_UID
GROUP BY 1, 2
ORDER BY P.STATE;


--19. Find (in months) average month it takes for new facilities to be established per LGA. 

SELECT P.LGA,
       AVG(DATE_PART('month', i.start_date)) -(SELECT DATE_PART('month', MIN(i.start_date))
            									FROM identifiers i) AS AVG_ESTABLISHMENT_DATE
            
FROM pages p
JOIN identifiers i ON P.FACILITY_UID = I.FACILITY_UID
GROUP BY 1
ORDER BY 1;

/*20. From your exploration, If you are to advise the Minister of Health, 
--which state or Region has the lowest should the Minister focus more on strengthening with more Facilities 
--and hiring more Health professionals */

--Number of Facilities Per state
SELECT STATE, COUNT(*)
FROM PAGES
GROUP BY 1
ORDER BY 2

/* The Minister of Health should strengthen Bayelsa,Ekiti, Rivers, Yobe, Gombe, FCT, Zamfara, 
Jigawa, Akwa-Ibom, Ondo, Ebonyi, Sokoto, Delta, Borno, and Kebbi with more facilities 
as they all have under a thousand facilities*/ 

--Number of health professionals per state
SELECT L.STATE,
    COALESCE(SUM(P.NUM_OF_DOCS), 0) + COALESCE(SUM(P.NUM_OF_PHARMS), 0) + COALESCE(SUM(P.NUM_OF_MIDWIFES), 0) + COALESCE(SUM(P.NUM_OF_NURSES), 0) + COALESCE(SUM(P.NUM_OF_NURSE_MIDWIFE), 0) + COALESCE(SUM(P.NUM_OF_PHARM_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_DENTISTS), 0) + COALESCE(SUM(P.NUM_OF_HEALTH_ATTENDANTS), 0) + COALESCE(SUM(P.NUM_OF_ENV_HEALTH_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_HIM_OFFICERS), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_HEALTH_OFFICER), 0) + COALESCE(SUM(P.NUM_OF_JUN_COMMUNITY_EXTENSION_WORKER), 0) + COALESCE(SUM(P.NUM_OF_COMMUNITY_EXTENSION_WORKERS), 0) + COALESCE(SUM(P.NUM_OF_DENTAL_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_TECHNICIANS), 0) + COALESCE(SUM(P.NUM_OF_LAB_SCIENTISTS), 0) AS TOTAL_PERSONNEL
FROM LOCATIONS L
JOIN PERSONNEL P ON L.FACILITY_UID = P.FACILITY_UID
WHERE L.STATE IS NOT NULL
GROUP BY L.STATE
ORDER BY 2;

/*The The Minister of Health should hire more professionals for Bayelsa, Sokoto, Ondo, Akwa-Ibom, 
Edo, and Abia as they all have under 5000 health professionals */
















